<?php

namespace Database\Seeders;

use App\Models\SetSubjectCoCurricularActivity;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SetSubjectCoCurricularActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Group 1
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'1',
            'ms_subject_co_curricular_activity_id'=>'13',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'1',
            'ms_subject_co_curricular_activity_id'=>'11',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'1',
            'ms_subject_co_curricular_activity_id'=>'2',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'1',
            'ms_subject_co_curricular_activity_id'=>'10',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'1',
            'ms_subject_co_curricular_activity_id'=>'8',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'1',
            'ms_subject_co_curricular_activity_id'=>'33',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        // Group 2
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'2',
            'ms_subject_co_curricular_activity_id'=>'13',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'2',
            'ms_subject_co_curricular_activity_id'=>'11',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'2',
            'ms_subject_co_curricular_activity_id'=>'2',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'2',
            'ms_subject_co_curricular_activity_id'=>'10',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'2',
            'ms_subject_co_curricular_activity_id'=>'8',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'2',
            'ms_subject_co_curricular_activity_id'=>'29',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        // Group 3
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'3',
            'ms_subject_co_curricular_activity_id'=>'11',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'3',
            'ms_subject_co_curricular_activity_id'=>'2',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'3',
            'ms_subject_co_curricular_activity_id'=>'10',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'3',
            'ms_subject_co_curricular_activity_id'=>'8',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'3',
            'ms_subject_co_curricular_activity_id'=>'14',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'3',
            'ms_subject_co_curricular_activity_id'=>'12',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        // Group 4
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'4',
            'ms_subject_co_curricular_activity_id'=>'11',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'4',
            'ms_subject_co_curricular_activity_id'=>'2',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'4',
            'ms_subject_co_curricular_activity_id'=>'10',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'4',
            'ms_subject_co_curricular_activity_id'=>'8',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'4',
            'ms_subject_co_curricular_activity_id'=>'14',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'4',
            'ms_subject_co_curricular_activity_id'=>'12',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        // Group 5
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'5',
            'ms_subject_co_curricular_activity_id'=>'11',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'5',
            'ms_subject_co_curricular_activity_id'=>'2',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'5',
            'ms_subject_co_curricular_activity_id'=>'10',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'5',
            'ms_subject_co_curricular_activity_id'=>'8',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'5',
            'ms_subject_co_curricular_activity_id'=>'14',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'5',
            'ms_subject_co_curricular_activity_id'=>'12',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        // Group 6
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'6',
            'ms_subject_co_curricular_activity_id'=>'11',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'6',
            'ms_subject_co_curricular_activity_id'=>'2',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'6',
            'ms_subject_co_curricular_activity_id'=>'10',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'6',
            'ms_subject_co_curricular_activity_id'=>'12',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'6',
            'ms_subject_co_curricular_activity_id'=>'8',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'6',
            'ms_subject_co_curricular_activity_id'=>'14',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
        SetSubjectCoCurricularActivity::create([
            'ms_group_id'=>'6',
            'ms_subject_co_curricular_activity_id'=>'41',
            'quota'=>mt_rand(5,15),
            'semester'=>'1',
            'academic_year'=>'2025/2026',
            'unit'=>'SD',
            'campus'=>'LAS',
        ]);
    }
}
